// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grps_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*StatusRegistrationAuthResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*StatusRegistrationAuthResponse, error)
	AddContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetContacts(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*GetContactsResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Disconnect(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusResponse, error)
	AcceptRequestContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeclineRequestContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ChatSession(ctx context.Context, opts ...grpc.CallOption) (Greeter_ChatSessionClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*StatusRegistrationAuthResponse, error) {
	out := new(StatusRegistrationAuthResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/Registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*StatusRegistrationAuthResponse, error) {
	out := new(StatusRegistrationAuthResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AddContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetContacts(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*GetContactsResponse, error) {
	out := new(GetContactsResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/GetContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Disconnect(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AcceptRequestContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/AcceptRequestContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeclineRequestContact(ctx context.Context, in *NewContactRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/chat.Greeter/DeclineRequestContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) ChatSession(ctx context.Context, opts ...grpc.CallOption) (Greeter_ChatSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/chat.Greeter/ChatSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterChatSessionClient{stream}
	return x, nil
}

type Greeter_ChatSessionClient interface {
	Send(*InputMsg) error
	Recv() (*OutputMsg, error)
	grpc.ClientStream
}

type greeterChatSessionClient struct {
	grpc.ClientStream
}

func (x *greeterChatSessionClient) Send(m *InputMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterChatSessionClient) Recv() (*OutputMsg, error) {
	m := new(OutputMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	Registration(context.Context, *RegistrationRequest) (*StatusRegistrationAuthResponse, error)
	Auth(context.Context, *AuthRequest) (*StatusRegistrationAuthResponse, error)
	AddContact(context.Context, *NewContactRequest) (*StatusResponse, error)
	GetContacts(context.Context, *EmptyMsg) (*GetContactsResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*StatusResponse, error)
	Disconnect(context.Context, *EmptyMsg) (*StatusResponse, error)
	AcceptRequestContact(context.Context, *NewContactRequest) (*StatusResponse, error)
	DeclineRequestContact(context.Context, *NewContactRequest) (*StatusResponse, error)
	ChatSession(Greeter_ChatSessionServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) Registration(context.Context, *RegistrationRequest) (*StatusRegistrationAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedGreeterServer) Auth(context.Context, *AuthRequest) (*StatusRegistrationAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedGreeterServer) AddContact(context.Context, *NewContactRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (UnimplementedGreeterServer) GetContacts(context.Context, *EmptyMsg) (*GetContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContacts not implemented")
}
func (UnimplementedGreeterServer) DeleteContact(context.Context, *DeleteContactRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (UnimplementedGreeterServer) Disconnect(context.Context, *EmptyMsg) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedGreeterServer) AcceptRequestContact(context.Context, *NewContactRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptRequestContact not implemented")
}
func (UnimplementedGreeterServer) DeclineRequestContact(context.Context, *NewContactRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineRequestContact not implemented")
}
func (UnimplementedGreeterServer) ChatSession(Greeter_ChatSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatSession not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Registration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AddContact(ctx, req.(*NewContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/GetContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetContacts(ctx, req.(*EmptyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Disconnect(ctx, req.(*EmptyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AcceptRequestContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AcceptRequestContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/AcceptRequestContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AcceptRequestContact(ctx, req.(*NewContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeclineRequestContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeclineRequestContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Greeter/DeclineRequestContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeclineRequestContact(ctx, req.(*NewContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_ChatSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ChatSession(&greeterChatSessionServer{stream})
}

type Greeter_ChatSessionServer interface {
	Send(*OutputMsg) error
	Recv() (*InputMsg, error)
	grpc.ServerStream
}

type greeterChatSessionServer struct {
	grpc.ServerStream
}

func (x *greeterChatSessionServer) Send(m *OutputMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterChatSessionServer) Recv() (*InputMsg, error) {
	m := new(InputMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _Greeter_Registration_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Greeter_Auth_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _Greeter_AddContact_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _Greeter_GetContacts_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _Greeter_DeleteContact_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Greeter_Disconnect_Handler,
		},
		{
			MethodName: "AcceptRequestContact",
			Handler:    _Greeter_AcceptRequestContact_Handler,
		},
		{
			MethodName: "DeclineRequestContact",
			Handler:    _Greeter_DeclineRequestContact_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatSession",
			Handler:       _Greeter_ChatSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
