// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto

#include "client.pb.h"
#include "client.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chat {

static const char* Greeter_method_names[] = {
  "/chat.Greeter/Registration",
  "/chat.Greeter/Auth",
  "/chat.Greeter/AddContact",
  "/chat.Greeter/GetContacts",
  "/chat.Greeter/DeleteContact",
  "/chat.Greeter/Disconnect",
  "/chat.Greeter/AcceptRequestContact",
  "/chat.Greeter/DeclineRequestContact",
  "/chat.Greeter/ChatSession",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Registration_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Auth_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddContact_(Greeter_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContacts_(Greeter_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteContact_(Greeter_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Disconnect_(Greeter_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AcceptRequestContact_(Greeter_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeclineRequestContact_(Greeter_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ChatSession_(Greeter_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::chat::StatusRegistrationAuthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Registration_, context, request, response);
}

void Greeter::Stub::async::Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Registration_, context, request, response, std::move(f));
}

void Greeter::Stub::async::Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Registration_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* Greeter::Stub::PrepareAsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusRegistrationAuthResponse, ::chat::RegistrationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Registration_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* Greeter::Stub::AsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegistrationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::Auth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::chat::StatusRegistrationAuthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Auth_, context, request, response);
}

void Greeter::Stub::async::Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Auth_, context, request, response, std::move(f));
}

void Greeter::Stub::async::Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Auth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* Greeter::Stub::PrepareAsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusRegistrationAuthResponse, ::chat::AuthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Auth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* Greeter::Stub::AsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddContact_, context, request, response);
}

void Greeter::Stub::async::AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddContact_, context, request, response, std::move(f));
}

void Greeter::Stub::async::AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddContact_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::PrepareAsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusResponse, ::chat::NewContactRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddContact_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::AsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddContactRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::GetContactsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::EmptyMsg, ::chat::GetContactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContacts_, context, request, response);
}

void Greeter::Stub::async::GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::EmptyMsg, ::chat::GetContactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, std::move(f));
}

void Greeter::Stub::async::GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>* Greeter::Stub::PrepareAsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::GetContactsResponse, ::chat::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContacts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>* Greeter::Stub::AsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContactsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::chat::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::DeleteContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteContact_, context, request, response);
}

void Greeter::Stub::async::DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::DeleteContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContact_, context, request, response, std::move(f));
}

void Greeter::Stub::async::DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContact_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::PrepareAsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusResponse, ::chat::DeleteContactRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteContact_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::AsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteContactRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::EmptyMsg, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Disconnect_, context, request, response);
}

void Greeter::Stub::async::Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::EmptyMsg, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, std::move(f));
}

void Greeter::Stub::async::Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Disconnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusResponse, ::chat::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Disconnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::AsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDisconnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AcceptRequestContact_, context, request, response);
}

void Greeter::Stub::async::AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcceptRequestContact_, context, request, response, std::move(f));
}

void Greeter::Stub::async::AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcceptRequestContact_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::PrepareAsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusResponse, ::chat::NewContactRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AcceptRequestContact_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::AsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcceptRequestContactRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Greeter::Stub::DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeclineRequestContact_, context, request, response);
}

void Greeter::Stub::async::DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeclineRequestContact_, context, request, response, std::move(f));
}

void Greeter::Stub::async::DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeclineRequestContact_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::PrepareAsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::StatusResponse, ::chat::NewContactRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeclineRequestContact_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* Greeter::Stub::AsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeclineRequestContactRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* Greeter::Stub::ChatSessionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::chat::InputMsg, ::chat::OutpuMsg>::Create(channel_.get(), rpcmethod_ChatSession_, context);
}

void Greeter::Stub::async::ChatSession(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::chat::InputMsg,::chat::OutpuMsg>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::chat::InputMsg,::chat::OutpuMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_ChatSession_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* Greeter::Stub::AsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::InputMsg, ::chat::OutpuMsg>::Create(channel_.get(), cq, rpcmethod_ChatSession_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* Greeter::Stub::PrepareAsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::InputMsg, ::chat::OutpuMsg>::Create(channel_.get(), cq, rpcmethod_ChatSession_, context, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::RegistrationRequest* req,
             ::chat::StatusRegistrationAuthResponse* resp) {
               return service->Registration(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::AuthRequest* req,
             ::chat::StatusRegistrationAuthResponse* resp) {
               return service->Auth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::NewContactRequest* req,
             ::chat::StatusResponse* resp) {
               return service->AddContact(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::EmptyMsg, ::chat::GetContactsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::EmptyMsg* req,
             ::chat::GetContactsResponse* resp) {
               return service->GetContacts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::DeleteContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::DeleteContactRequest* req,
             ::chat::StatusResponse* resp) {
               return service->DeleteContact(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::EmptyMsg, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::EmptyMsg* req,
             ::chat::StatusResponse* resp) {
               return service->Disconnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::NewContactRequest* req,
             ::chat::StatusResponse* resp) {
               return service->AcceptRequestContact(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::chat::NewContactRequest, ::chat::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::NewContactRequest* req,
             ::chat::StatusResponse* resp) {
               return service->DeclineRequestContact(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[8],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Greeter::Service, ::chat::InputMsg, ::chat::OutpuMsg>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::chat::OutpuMsg,
             ::chat::InputMsg>* stream) {
               return service->ChatSession(ctx, stream);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::Registration(::grpc::ServerContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Auth(::grpc::ServerContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::AddContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::GetContacts(::grpc::ServerContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::DeleteContact(::grpc::ServerContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Disconnect(::grpc::ServerContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::AcceptRequestContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::DeclineRequestContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::ChatSession(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

