// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto
#ifndef GRPC_client_2eproto__INCLUDED
#define GRPC_client_2eproto__INCLUDED

#include "client.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace chat {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "chat.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::chat::StatusRegistrationAuthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>> AsyncRegistration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>>(AsyncRegistrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>> PrepareAsyncRegistration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>>(PrepareAsyncRegistrationRaw(context, request, cq));
    }
    virtual ::grpc::Status Auth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::chat::StatusRegistrationAuthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>> AsyncAuth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>>(AsyncAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>> PrepareAsyncAuth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>>(PrepareAsyncAuthRaw(context, request, cq));
    }
    virtual ::grpc::Status AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> AsyncAddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(AsyncAddContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> PrepareAsyncAddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(PrepareAsyncAddContactRaw(context, request, cq));
    }
    virtual ::grpc::Status GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::GetContactsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>> AsyncGetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>>(AsyncGetContactsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>> PrepareAsyncGetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>>(PrepareAsyncGetContactsRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::chat::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> AsyncDeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(AsyncDeleteContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> PrepareAsyncDeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(PrepareAsyncDeleteContactRaw(context, request, cq));
    }
    virtual ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> AsyncDisconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    virtual ::grpc::Status AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> AsyncAcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(AsyncAcceptRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> PrepareAsyncAcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(PrepareAsyncAcceptRequestContactRaw(context, request, cq));
    }
    virtual ::grpc::Status DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> AsyncDeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(AsyncDeclineRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>> PrepareAsyncDeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>>(PrepareAsyncDeclineRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>> ChatSession(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>>(ChatSessionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>> AsyncChatSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>>(AsyncChatSessionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>> PrepareAsyncChatSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>>(PrepareAsyncChatSessionRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ChatSession(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::chat::InputMsg,::chat::OutpuMsg>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>* AsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>* PrepareAsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>* AsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusRegistrationAuthResponse>* PrepareAsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* AsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* PrepareAsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>* AsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::GetContactsResponse>* PrepareAsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* AsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* PrepareAsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* AsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* PrepareAsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* AsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat::StatusResponse>* PrepareAsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>* ChatSessionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>* AsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::chat::InputMsg, ::chat::OutpuMsg>* PrepareAsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::chat::StatusRegistrationAuthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>> AsyncRegistration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>>(AsyncRegistrationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>> PrepareAsyncRegistration(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>>(PrepareAsyncRegistrationRaw(context, request, cq));
    }
    ::grpc::Status Auth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::chat::StatusRegistrationAuthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>> AsyncAuth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>>(AsyncAuthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>> PrepareAsyncAuth(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>>(PrepareAsyncAuthRaw(context, request, cq));
    }
    ::grpc::Status AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> AsyncAddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(AsyncAddContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> PrepareAsyncAddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(PrepareAsyncAddContactRaw(context, request, cq));
    }
    ::grpc::Status GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::GetContactsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>> AsyncGetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>>(AsyncGetContactsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>> PrepareAsyncGetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>>(PrepareAsyncGetContactsRaw(context, request, cq));
    }
    ::grpc::Status DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::chat::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> AsyncDeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(AsyncDeleteContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> PrepareAsyncDeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(PrepareAsyncDeleteContactRaw(context, request, cq));
    }
    ::grpc::Status Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::chat::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> AsyncDisconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(AsyncDisconnectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> PrepareAsyncDisconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(PrepareAsyncDisconnectRaw(context, request, cq));
    }
    ::grpc::Status AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> AsyncAcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(AsyncAcceptRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> PrepareAsyncAcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(PrepareAsyncAcceptRequestContactRaw(context, request, cq));
    }
    ::grpc::Status DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::chat::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> AsyncDeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(AsyncDeclineRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>> PrepareAsyncDeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>>(PrepareAsyncDeclineRequestContactRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>> ChatSession(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>>(ChatSessionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>> AsyncChatSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>>(AsyncChatSessionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>> PrepareAsyncChatSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>>(PrepareAsyncChatSessionRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)>) override;
      void Registration(::grpc::ClientContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, std::function<void(::grpc::Status)>) override;
      void Auth(::grpc::ClientContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void AddContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetContacts(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteContact(::grpc::ClientContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void Disconnect(::grpc::ClientContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void AcceptRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void DeclineRequestContact(::grpc::ClientContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ChatSession(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::chat::InputMsg,::chat::OutpuMsg>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* AsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* PrepareAsyncRegistrationRaw(::grpc::ClientContext* context, const ::chat::RegistrationRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* AsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusRegistrationAuthResponse>* PrepareAsyncAuthRaw(::grpc::ClientContext* context, const ::chat::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* AsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* PrepareAsyncAddContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>* AsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::GetContactsResponse>* PrepareAsyncGetContactsRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* AsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* PrepareAsyncDeleteContactRaw(::grpc::ClientContext* context, const ::chat::DeleteContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* AsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* PrepareAsyncDisconnectRaw(::grpc::ClientContext* context, const ::chat::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* AsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* PrepareAsyncAcceptRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* AsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat::StatusResponse>* PrepareAsyncDeclineRequestContactRaw(::grpc::ClientContext* context, const ::chat::NewContactRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* ChatSessionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* AsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::chat::InputMsg, ::chat::OutpuMsg>* PrepareAsyncChatSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Registration_;
    const ::grpc::internal::RpcMethod rpcmethod_Auth_;
    const ::grpc::internal::RpcMethod rpcmethod_AddContact_;
    const ::grpc::internal::RpcMethod rpcmethod_GetContacts_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteContact_;
    const ::grpc::internal::RpcMethod rpcmethod_Disconnect_;
    const ::grpc::internal::RpcMethod rpcmethod_AcceptRequestContact_;
    const ::grpc::internal::RpcMethod rpcmethod_DeclineRequestContact_;
    const ::grpc::internal::RpcMethod rpcmethod_ChatSession_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Registration(::grpc::ServerContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response);
    virtual ::grpc::Status Auth(::grpc::ServerContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response);
    virtual ::grpc::Status AddContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response);
    virtual ::grpc::Status GetContacts(::grpc::ServerContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response);
    virtual ::grpc::Status DeleteContact(::grpc::ServerContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response);
    virtual ::grpc::Status Disconnect(::grpc::ServerContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response);
    virtual ::grpc::Status AcceptRequestContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response);
    virtual ::grpc::Status DeclineRequestContact(::grpc::ServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response);
    virtual ::grpc::Status ChatSession(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Registration() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegistration(::grpc::ServerContext* context, ::chat::RegistrationRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusRegistrationAuthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Auth() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuth(::grpc::ServerContext* context, ::chat::AuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusRegistrationAuthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddContact() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddContact(::grpc::ServerContext* context, ::chat::NewContactRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetContacts() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContacts(::grpc::ServerContext* context, ::chat::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::chat::GetContactsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteContact() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContact(::grpc::ServerContext* context, ::chat::DeleteContactRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Disconnect() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::chat::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAcceptRequestContact(::grpc::ServerContext* context, ::chat::NewContactRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeclineRequestContact(::grpc::ServerContext* context, ::chat::NewContactRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ChatSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ChatSession() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_ChatSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(8, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Registration<WithAsyncMethod_Auth<WithAsyncMethod_AddContact<WithAsyncMethod_GetContacts<WithAsyncMethod_DeleteContact<WithAsyncMethod_Disconnect<WithAsyncMethod_AcceptRequestContact<WithAsyncMethod_DeclineRequestContact<WithAsyncMethod_ChatSession<Service > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Registration() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::RegistrationRequest* request, ::chat::StatusRegistrationAuthResponse* response) { return this->Registration(context, request, response); }));}
    void SetMessageAllocatorFor_Registration(
        ::grpc::MessageAllocator< ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Registration(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Auth() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::AuthRequest* request, ::chat::StatusRegistrationAuthResponse* response) { return this->Auth(context, request, response); }));}
    void SetMessageAllocatorFor_Auth(
        ::grpc::MessageAllocator< ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Auth(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddContact() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) { return this->AddContact(context, request, response); }));}
    void SetMessageAllocatorFor_AddContact(
        ::grpc::MessageAllocator< ::chat::NewContactRequest, ::chat::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddContact(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetContacts() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::EmptyMsg, ::chat::GetContactsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::EmptyMsg* request, ::chat::GetContactsResponse* response) { return this->GetContacts(context, request, response); }));}
    void SetMessageAllocatorFor_GetContacts(
        ::grpc::MessageAllocator< ::chat::EmptyMsg, ::chat::GetContactsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::EmptyMsg, ::chat::GetContactsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetContacts(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteContact() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::DeleteContactRequest, ::chat::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::DeleteContactRequest* request, ::chat::StatusResponse* response) { return this->DeleteContact(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteContact(
        ::grpc::MessageAllocator< ::chat::DeleteContactRequest, ::chat::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::DeleteContactRequest, ::chat::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContact(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::EmptyMsg, ::chat::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::EmptyMsg* request, ::chat::StatusResponse* response) { return this->Disconnect(context, request, response); }));}
    void SetMessageAllocatorFor_Disconnect(
        ::grpc::MessageAllocator< ::chat::EmptyMsg, ::chat::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::EmptyMsg, ::chat::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) { return this->AcceptRequestContact(context, request, response); }));}
    void SetMessageAllocatorFor_AcceptRequestContact(
        ::grpc::MessageAllocator< ::chat::NewContactRequest, ::chat::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AcceptRequestContact(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat::NewContactRequest* request, ::chat::StatusResponse* response) { return this->DeclineRequestContact(context, request, response); }));}
    void SetMessageAllocatorFor_DeclineRequestContact(
        ::grpc::MessageAllocator< ::chat::NewContactRequest, ::chat::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat::NewContactRequest, ::chat::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeclineRequestContact(
      ::grpc::CallbackServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ChatSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ChatSession() {
      ::grpc::Service::MarkMethodCallback(8,
          new ::grpc::internal::CallbackBidiHandler< ::chat::InputMsg, ::chat::OutpuMsg>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ChatSession(context); }));
    }
    ~WithCallbackMethod_ChatSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::chat::InputMsg, ::chat::OutpuMsg>* ChatSession(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Registration<WithCallbackMethod_Auth<WithCallbackMethod_AddContact<WithCallbackMethod_GetContacts<WithCallbackMethod_DeleteContact<WithCallbackMethod_Disconnect<WithCallbackMethod_AcceptRequestContact<WithCallbackMethod_DeclineRequestContact<WithCallbackMethod_ChatSession<Service > > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Registration() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Auth() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddContact() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetContacts() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteContact() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Disconnect() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ChatSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ChatSession() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_ChatSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Registration() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegistration(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Auth() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddContact() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddContact(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetContacts() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContacts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteContact() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContact(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Disconnect() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDisconnect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAcceptRequestContact(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeclineRequestContact(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ChatSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ChatSession() {
      ::grpc::Service::MarkMethodRaw(8);
    }
    ~WithRawMethod_ChatSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(8, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Registration() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Registration(context, request, response); }));
    }
    ~WithRawCallbackMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Registration(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Auth() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Auth(context, request, response); }));
    }
    ~WithRawCallbackMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Auth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddContact() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddContact(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddContact(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetContacts() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetContacts(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetContacts(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteContact() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteContact(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContact(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Disconnect() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Disconnect(context, request, response); }));
    }
    ~WithRawCallbackMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Disconnect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AcceptRequestContact(context, request, response); }));
    }
    ~WithRawCallbackMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AcceptRequestContact(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeclineRequestContact(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeclineRequestContact(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ChatSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ChatSession() {
      ::grpc::Service::MarkMethodRawCallback(8,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ChatSession(context); }));
    }
    ~WithRawCallbackMethod_ChatSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatSession(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::chat::OutpuMsg, ::chat::InputMsg>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ChatSession(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Registration : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Registration() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::RegistrationRequest, ::chat::StatusRegistrationAuthResponse>* streamer) {
                       return this->StreamedRegistration(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Registration() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Registration(::grpc::ServerContext* /*context*/, const ::chat::RegistrationRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegistration(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::RegistrationRequest,::chat::StatusRegistrationAuthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Auth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Auth() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::AuthRequest, ::chat::StatusRegistrationAuthResponse>* streamer) {
                       return this->StreamedAuth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Auth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Auth(::grpc::ServerContext* /*context*/, const ::chat::AuthRequest* /*request*/, ::chat::StatusRegistrationAuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::AuthRequest,::chat::StatusRegistrationAuthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddContact() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::NewContactRequest, ::chat::StatusResponse>* streamer) {
                       return this->StreamedAddContact(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddContact(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::NewContactRequest,::chat::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetContacts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetContacts() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::EmptyMsg, ::chat::GetContactsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::EmptyMsg, ::chat::GetContactsResponse>* streamer) {
                       return this->StreamedGetContacts(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetContacts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetContacts(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::GetContactsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetContacts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::EmptyMsg,::chat::GetContactsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteContact() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::DeleteContactRequest, ::chat::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::DeleteContactRequest, ::chat::StatusResponse>* streamer) {
                       return this->StreamedDeleteContact(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteContact(::grpc::ServerContext* /*context*/, const ::chat::DeleteContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteContact(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::DeleteContactRequest,::chat::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Disconnect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Disconnect() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::EmptyMsg, ::chat::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::EmptyMsg, ::chat::StatusResponse>* streamer) {
                       return this->StreamedDisconnect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Disconnect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Disconnect(::grpc::ServerContext* /*context*/, const ::chat::EmptyMsg* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDisconnect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::EmptyMsg,::chat::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AcceptRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AcceptRequestContact() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::NewContactRequest, ::chat::StatusResponse>* streamer) {
                       return this->StreamedAcceptRequestContact(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AcceptRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AcceptRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAcceptRequestContact(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::NewContactRequest,::chat::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeclineRequestContact : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeclineRequestContact() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat::NewContactRequest, ::chat::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat::NewContactRequest, ::chat::StatusResponse>* streamer) {
                       return this->StreamedDeclineRequestContact(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeclineRequestContact() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeclineRequestContact(::grpc::ServerContext* /*context*/, const ::chat::NewContactRequest* /*request*/, ::chat::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeclineRequestContact(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat::NewContactRequest,::chat::StatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Registration<WithStreamedUnaryMethod_Auth<WithStreamedUnaryMethod_AddContact<WithStreamedUnaryMethod_GetContacts<WithStreamedUnaryMethod_DeleteContact<WithStreamedUnaryMethod_Disconnect<WithStreamedUnaryMethod_AcceptRequestContact<WithStreamedUnaryMethod_DeclineRequestContact<Service > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Registration<WithStreamedUnaryMethod_Auth<WithStreamedUnaryMethod_AddContact<WithStreamedUnaryMethod_GetContacts<WithStreamedUnaryMethod_DeleteContact<WithStreamedUnaryMethod_Disconnect<WithStreamedUnaryMethod_AcceptRequestContact<WithStreamedUnaryMethod_DeclineRequestContact<Service > > > > > > > > StreamedService;
};

}  // namespace chat


#endif  // GRPC_client_2eproto__INCLUDED
