services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DataBaseRootPassword}
      MYSQL_DATABASE: ${DataBaseName}
      MYSQL_USER: ${DataBaseUser}
      MYSQL_PASSWORD: ${DataBaseUserPassword}
    networks:
      - chat-network

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: ${MQRabbitUser}
      RABBITMQ_DEFAULT_PASS: ${MQRabbitUserPassword}
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - chat-network
      
  app:
    build: .
    ports:
      - "50051:50051"
    restart: always
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DataBaseURLCoonntection=${DataBaseURLCoonntection}
      - JWTTokenSecret=${JWTTokenSecret}
      - MQRabbitURLConnection=${MQRabbitURLConnection}
      - MQRabbitMsgQueueName=${MQRabbitMsgQueueName}
    volumes:
      - .:/chat
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge