syntax = "proto3";

option go_package = "./internal/grps_chat";

package chat;

service Greeter {
    rpc Registration(RegistrationRequest) returns (StatusRegistrationAuthResponse);
    rpc Auth(AuthRequest) returns (StatusRegistrationAuthResponse);
    rpc AddContact(NewContactRequest) returns (StatusResponse);
    rpc GetContacts(EmptyMsg) returns (GetContactsResponse);
    rpc DeleteContact(DeleteContactRequest) returns (StatusResponse);
    rpc Disconnect(EmptyMsg) returns (StatusResponse);
    rpc AcceptRequestContact(NewContactRequest) returns (StatusResponse);
    rpc DeclineRequestContact(NewContactRequest) returns (StatusResponse);
    rpc ChatSession(stream ChatMsg) returns (stream ChatMsg);
} 

message StatusRegistrationAuthResponse {
    int64 status = 1;
    string token = 2;
}

message NewContactRequest {
    string contact = 1;
}

message DeleteContactRequest {
    string contact = 1;
}

message NewConversationRequest {
    string login = 1;
}

message GetContactsResponse {
    repeated string contats = 1;
    repeated int64 statuses = 2;
}



message EmptyMsg {

}

message RegistrationRequest {
    string login = 1;
    string password = 2;
}

message AuthRequest {
    string login = 1;
    string password = 2;
}

message StatusResponse {
    int64 status = 1;   
}

message NewChatMsg {
    string chat_id = 1;
    string sender = 2;
    string recipient = 3;
    int64 alg = 4;
    int64 enc_mode = 5;
    int64 padd_mode = 6;
    string g_for_key = 7;
    string p_for_key = 8;
    string AB_for_key = 9;
    string g_for_iv = 10;
    string p_for_iv = 11;
    string AB_for_iv = 12;   
    int64 status = 13;
}

message DefaultChatMsg {
    string chat_id = 1;
    string sender = 2;
    string recipient = 3;
    bytes data = 4;
    int64 timestamp = 5;
}

message FileMsg {
    string chat_id = 1;
    string sender = 2;
    string recipient = 3;
    int64 index_file_chunk = 4;
    int64 total_file_chunk = 5;
    bytes data = 6;
    int64 timestamp = 7;

}

message ChatMsg {
    oneof payload {
        NewChatMsg new_chat_msg = 1;
        FileMsg file_msg = 2;
        DefaultChatMsg default_msg = 3;
    }
}