syntax = "proto3";

option go_package = "./internal/grps_chat";

package chat;

service Greeter {
    rpc Registration(RegistrationRequest) returns (StatusRegistrationAuthResponse);
    rpc Auth(AuthRequest) returns (StatusRegistrationAuthResponse);
    rpc AddContact(NewContactRequest) returns (StatusResponse);
    rpc GetContacts(EmptyMsg) returns (GetContactsResponse);
    rpc DeleteContact(DeleteContactRequest) returns (StatusResponse);
    rpc Disconnect(EmptyMsg) returns (StatusResponse);
    rpc AcceptRequestContact(NewContactRequest) returns (StatusResponse);
    rpc DeclineRequestContact(NewContactRequest) returns (StatusResponse);
    rpc ChatSession(stream InputMsg) returns (stream OutpuMsg);
} 

message StatusRegistrationAuthResponse {
    int64 status = 1;
    string token = 2;
}

message NewContactRequest {
    string contact = 1;
}

message DeleteContactRequest {
    string contact = 1;
}

message NewConversationRequest {
    string login = 1;
}

message GetContactsResponse {
    repeated string contats = 1;
    repeated int64 statuses = 2;
}



message EmptyMsg {

}

message RegistrationRequest {
    string login = 1;
    string password = 2;
}

message AuthRequest {
    string login = 1;
    string password = 2;
}

message StatusResponse {
    int64 status = 1;
}

message InputMsg {
    string sender = 1;
    string recipient = 2;
    bytes data = 3;
    int64 timestamp = 4;
    int64 statusMsg = 5;
    string id = 6;
    bool is_file = 7;
    int64 index_file_chunk = 8;
    int64 total_file_chunk = 9;
}

message OutpuMsg {
    string sender = 1;
    string recipient = 2;
    bytes data = 3;
    int64 timestamp = 4;
    int64 statusMsg = 5;
    string id = 6;
    bool is_file = 7;
    int64 index_file_chunk = 8;
    int64 total_file_chunk = 9;
}